### ISSUE TITLE
Human readable timestamps

### ISSUE THREAD

**Issue by CharlieWinters** [newrelic-experimental/nr1-multi-account-query#15]
Here was a request from a customer. Would it be possible to display human readable timestamps?

Example:
<img width="1649" alt="Multi_Account_Query___New_Relic_One" src="https://user-images.githubusercontent.com/10816343/131503965-aa255bc7-6f6e-476d-b7a5-528796e07210.png">

We're seeing the unix timstamp, however it would be useful if the table would show the time and date similar to nr1 dashboards.

**Comment by Thamaraisiva** [comment]
We are also looking for the same feature

**Comment by jsbnr** [comment]
I can look into this as an option. I will need to think of a elegant way to detect if its a timestamp and then format...

**Comment by Thamaraisiva** [comment]
> I can look into this as an option. I will need to think of a elegant way to detect if its a timestamp and then format...

It would be nice if you could fix this

**Comment by jsbnr** [comment]
I found a solution that I think works nicely, merged as PR #16

**Comment by jsbnr** [comment]
Closing issue, thanks for the feature request.
